# Generated by Django 3.2.9 on 2021-12-04 20:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_rounds_won', models.IntegerField()),
                ('p2_rounds_won', models.IntegerField()),
                ('p1_is_winner', models.BooleanField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('p1_char', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_p1', to='characters.character')),
                ('p2_char', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_p2', to='characters.character')),
                ('player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_p1', to='players.player')),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_p2', to='players.player')),
            ],
        ),
    ]
